# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/xuxiaoyu/ClionProjects/commonconfig

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/xuxiaoyu/ClionProjects/commonconfig

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/xuxiaoyu/ClionProjects/commonconfig/CMakeFiles /Users/xuxiaoyu/ClionProjects/commonconfig/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/xuxiaoyu/ClionProjects/commonconfig/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dbthread

# Build rule for target.
dbthread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dbthread
.PHONY : dbthread

# fast build rule for target.
dbthread/fast:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/build
.PHONY : dbthread/fast

#=============================================================================
# Target rules for targets named commonconfig

# Build rule for target.
commonconfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 commonconfig
.PHONY : commonconfig

# fast build rule for target.
commonconfig/fast:
	$(MAKE) -f CMakeFiles/commonconfig.dir/build.make CMakeFiles/commonconfig.dir/build
.PHONY : commonconfig/fast

Db/Connection.o: Db/Connection.cpp.o

.PHONY : Db/Connection.o

# target to build an object file
Db/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/Connection.cpp.o
.PHONY : Db/Connection.cpp.o

Db/Connection.i: Db/Connection.cpp.i

.PHONY : Db/Connection.i

# target to preprocess a source file
Db/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/Connection.cpp.i
.PHONY : Db/Connection.cpp.i

Db/Connection.s: Db/Connection.cpp.s

.PHONY : Db/Connection.s

# target to generate assembly for a file
Db/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/Connection.cpp.s
.PHONY : Db/Connection.cpp.s

Db/ConnectionPool.o: Db/ConnectionPool.cpp.o

.PHONY : Db/ConnectionPool.o

# target to build an object file
Db/ConnectionPool.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/ConnectionPool.cpp.o
.PHONY : Db/ConnectionPool.cpp.o

Db/ConnectionPool.i: Db/ConnectionPool.cpp.i

.PHONY : Db/ConnectionPool.i

# target to preprocess a source file
Db/ConnectionPool.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/ConnectionPool.cpp.i
.PHONY : Db/ConnectionPool.cpp.i

Db/ConnectionPool.s: Db/ConnectionPool.cpp.s

.PHONY : Db/ConnectionPool.s

# target to generate assembly for a file
Db/ConnectionPool.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/ConnectionPool.cpp.s
.PHONY : Db/ConnectionPool.cpp.s

Db/ConnectionWorker.o: Db/ConnectionWorker.cpp.o

.PHONY : Db/ConnectionWorker.o

# target to build an object file
Db/ConnectionWorker.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/ConnectionWorker.cpp.o
.PHONY : Db/ConnectionWorker.cpp.o

Db/ConnectionWorker.i: Db/ConnectionWorker.cpp.i

.PHONY : Db/ConnectionWorker.i

# target to preprocess a source file
Db/ConnectionWorker.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/ConnectionWorker.cpp.i
.PHONY : Db/ConnectionWorker.cpp.i

Db/ConnectionWorker.s: Db/ConnectionWorker.cpp.s

.PHONY : Db/ConnectionWorker.s

# target to generate assembly for a file
Db/ConnectionWorker.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/ConnectionWorker.cpp.s
.PHONY : Db/ConnectionWorker.cpp.s

Db/DbBase.o: Db/DbBase.cpp.o

.PHONY : Db/DbBase.o

# target to build an object file
Db/DbBase.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/DbBase.cpp.o
.PHONY : Db/DbBase.cpp.o

Db/DbBase.i: Db/DbBase.cpp.i

.PHONY : Db/DbBase.i

# target to preprocess a source file
Db/DbBase.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/DbBase.cpp.i
.PHONY : Db/DbBase.cpp.i

Db/DbBase.s: Db/DbBase.cpp.s

.PHONY : Db/DbBase.s

# target to generate assembly for a file
Db/DbBase.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/Db/DbBase.cpp.s
.PHONY : Db/DbBase.cpp.s

Server.o: Server.cpp.o

.PHONY : Server.o

# target to build an object file
Server.cpp.o:
	$(MAKE) -f CMakeFiles/commonconfig.dir/build.make CMakeFiles/commonconfig.dir/Server.cpp.o
.PHONY : Server.cpp.o

Server.i: Server.cpp.i

.PHONY : Server.i

# target to preprocess a source file
Server.cpp.i:
	$(MAKE) -f CMakeFiles/commonconfig.dir/build.make CMakeFiles/commonconfig.dir/Server.cpp.i
.PHONY : Server.cpp.i

Server.s: Server.cpp.s

.PHONY : Server.s

# target to generate assembly for a file
Server.cpp.s:
	$(MAKE) -f CMakeFiles/commonconfig.dir/build.make CMakeFiles/commonconfig.dir/Server.cpp.s
.PHONY : Server.cpp.s

ThreadPool/CCondition.o: ThreadPool/CCondition.cpp.o

.PHONY : ThreadPool/CCondition.o

# target to build an object file
ThreadPool/CCondition.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CCondition.cpp.o
.PHONY : ThreadPool/CCondition.cpp.o

ThreadPool/CCondition.i: ThreadPool/CCondition.cpp.i

.PHONY : ThreadPool/CCondition.i

# target to preprocess a source file
ThreadPool/CCondition.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CCondition.cpp.i
.PHONY : ThreadPool/CCondition.cpp.i

ThreadPool/CCondition.s: ThreadPool/CCondition.cpp.s

.PHONY : ThreadPool/CCondition.s

# target to generate assembly for a file
ThreadPool/CCondition.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CCondition.cpp.s
.PHONY : ThreadPool/CCondition.cpp.s

ThreadPool/CJob.o: ThreadPool/CJob.cpp.o

.PHONY : ThreadPool/CJob.o

# target to build an object file
ThreadPool/CJob.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CJob.cpp.o
.PHONY : ThreadPool/CJob.cpp.o

ThreadPool/CJob.i: ThreadPool/CJob.cpp.i

.PHONY : ThreadPool/CJob.i

# target to preprocess a source file
ThreadPool/CJob.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CJob.cpp.i
.PHONY : ThreadPool/CJob.cpp.i

ThreadPool/CJob.s: ThreadPool/CJob.cpp.s

.PHONY : ThreadPool/CJob.s

# target to generate assembly for a file
ThreadPool/CJob.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CJob.cpp.s
.PHONY : ThreadPool/CJob.cpp.s

ThreadPool/CThread.o: ThreadPool/CThread.cpp.o

.PHONY : ThreadPool/CThread.o

# target to build an object file
ThreadPool/CThread.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThread.cpp.o
.PHONY : ThreadPool/CThread.cpp.o

ThreadPool/CThread.i: ThreadPool/CThread.cpp.i

.PHONY : ThreadPool/CThread.i

# target to preprocess a source file
ThreadPool/CThread.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThread.cpp.i
.PHONY : ThreadPool/CThread.cpp.i

ThreadPool/CThread.s: ThreadPool/CThread.cpp.s

.PHONY : ThreadPool/CThread.s

# target to generate assembly for a file
ThreadPool/CThread.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThread.cpp.s
.PHONY : ThreadPool/CThread.cpp.s

ThreadPool/CThreadManage.o: ThreadPool/CThreadManage.cpp.o

.PHONY : ThreadPool/CThreadManage.o

# target to build an object file
ThreadPool/CThreadManage.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadManage.cpp.o
.PHONY : ThreadPool/CThreadManage.cpp.o

ThreadPool/CThreadManage.i: ThreadPool/CThreadManage.cpp.i

.PHONY : ThreadPool/CThreadManage.i

# target to preprocess a source file
ThreadPool/CThreadManage.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadManage.cpp.i
.PHONY : ThreadPool/CThreadManage.cpp.i

ThreadPool/CThreadManage.s: ThreadPool/CThreadManage.cpp.s

.PHONY : ThreadPool/CThreadManage.s

# target to generate assembly for a file
ThreadPool/CThreadManage.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadManage.cpp.s
.PHONY : ThreadPool/CThreadManage.cpp.s

ThreadPool/CThreadMutex.o: ThreadPool/CThreadMutex.cpp.o

.PHONY : ThreadPool/CThreadMutex.o

# target to build an object file
ThreadPool/CThreadMutex.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadMutex.cpp.o
.PHONY : ThreadPool/CThreadMutex.cpp.o

ThreadPool/CThreadMutex.i: ThreadPool/CThreadMutex.cpp.i

.PHONY : ThreadPool/CThreadMutex.i

# target to preprocess a source file
ThreadPool/CThreadMutex.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadMutex.cpp.i
.PHONY : ThreadPool/CThreadMutex.cpp.i

ThreadPool/CThreadMutex.s: ThreadPool/CThreadMutex.cpp.s

.PHONY : ThreadPool/CThreadMutex.s

# target to generate assembly for a file
ThreadPool/CThreadMutex.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadMutex.cpp.s
.PHONY : ThreadPool/CThreadMutex.cpp.s

ThreadPool/CThreadPool.o: ThreadPool/CThreadPool.cpp.o

.PHONY : ThreadPool/CThreadPool.o

# target to build an object file
ThreadPool/CThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadPool.cpp.o
.PHONY : ThreadPool/CThreadPool.cpp.o

ThreadPool/CThreadPool.i: ThreadPool/CThreadPool.cpp.i

.PHONY : ThreadPool/CThreadPool.i

# target to preprocess a source file
ThreadPool/CThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadPool.cpp.i
.PHONY : ThreadPool/CThreadPool.cpp.i

ThreadPool/CThreadPool.s: ThreadPool/CThreadPool.cpp.s

.PHONY : ThreadPool/CThreadPool.s

# target to generate assembly for a file
ThreadPool/CThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CThreadPool.cpp.s
.PHONY : ThreadPool/CThreadPool.cpp.s

ThreadPool/CWorkerThread.o: ThreadPool/CWorkerThread.cpp.o

.PHONY : ThreadPool/CWorkerThread.o

# target to build an object file
ThreadPool/CWorkerThread.cpp.o:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CWorkerThread.cpp.o
.PHONY : ThreadPool/CWorkerThread.cpp.o

ThreadPool/CWorkerThread.i: ThreadPool/CWorkerThread.cpp.i

.PHONY : ThreadPool/CWorkerThread.i

# target to preprocess a source file
ThreadPool/CWorkerThread.cpp.i:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CWorkerThread.cpp.i
.PHONY : ThreadPool/CWorkerThread.cpp.i

ThreadPool/CWorkerThread.s: ThreadPool/CWorkerThread.cpp.s

.PHONY : ThreadPool/CWorkerThread.s

# target to generate assembly for a file
ThreadPool/CWorkerThread.cpp.s:
	$(MAKE) -f CMakeFiles/dbthread.dir/build.make CMakeFiles/dbthread.dir/ThreadPool/CWorkerThread.cpp.s
.PHONY : ThreadPool/CWorkerThread.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/commonconfig.dir/build.make CMakeFiles/commonconfig.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/commonconfig.dir/build.make CMakeFiles/commonconfig.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/commonconfig.dir/build.make CMakeFiles/commonconfig.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dbthread"
	@echo "... commonconfig"
	@echo "... Db/Connection.o"
	@echo "... Db/Connection.i"
	@echo "... Db/Connection.s"
	@echo "... Db/ConnectionPool.o"
	@echo "... Db/ConnectionPool.i"
	@echo "... Db/ConnectionPool.s"
	@echo "... Db/ConnectionWorker.o"
	@echo "... Db/ConnectionWorker.i"
	@echo "... Db/ConnectionWorker.s"
	@echo "... Db/DbBase.o"
	@echo "... Db/DbBase.i"
	@echo "... Db/DbBase.s"
	@echo "... Server.o"
	@echo "... Server.i"
	@echo "... Server.s"
	@echo "... ThreadPool/CCondition.o"
	@echo "... ThreadPool/CCondition.i"
	@echo "... ThreadPool/CCondition.s"
	@echo "... ThreadPool/CJob.o"
	@echo "... ThreadPool/CJob.i"
	@echo "... ThreadPool/CJob.s"
	@echo "... ThreadPool/CThread.o"
	@echo "... ThreadPool/CThread.i"
	@echo "... ThreadPool/CThread.s"
	@echo "... ThreadPool/CThreadManage.o"
	@echo "... ThreadPool/CThreadManage.i"
	@echo "... ThreadPool/CThreadManage.s"
	@echo "... ThreadPool/CThreadMutex.o"
	@echo "... ThreadPool/CThreadMutex.i"
	@echo "... ThreadPool/CThreadMutex.s"
	@echo "... ThreadPool/CThreadPool.o"
	@echo "... ThreadPool/CThreadPool.i"
	@echo "... ThreadPool/CThreadPool.s"
	@echo "... ThreadPool/CWorkerThread.o"
	@echo "... ThreadPool/CWorkerThread.i"
	@echo "... ThreadPool/CWorkerThread.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

